repos:
  - repo: https://github.com/realm/SwiftLint
    rev: 0.50.3
    hooks:
      - id: swiftlint
  - repo: https://github.com/nicklockwood/SwiftFormat
    rev: 0.52.4
    hooks:
      - id: swiftformat
        args: ['--swiftversion', '5.7.2']
